### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lgmgeo**
Add documentation for AnnotSV user in the README.md

### CODE REVIEW

**Comment by SamuelNicaise** [comment]
Those are very minor remarks... Usually I would edit the pull request myself then merge, but I think I can't as it is forked from your repository? In any case thanks a lot for those additions

**Comment by lgmgeo** [comment]
There is a new section dedicated to AnnotSV

**Comment by lgmgeo** [comment]
(in the README)

**Comment by SamuelNicaise** [comment]
What I meant was the reviews I made on your pull requests are minor. Can you see them?

**Comment by lgmgeo** [comment]
I can't see anything (only your comment) ;o(

It doesn't matter, you can delete my pull request (if you integrated the new documentation by yourself, the result will be the same)

**Comment by SamuelNicaise** [comment]
Added new doc in 868781f0750ceb015132155f21471fb8b8aa3882 and logos in 5e5b3dae761f8b4d4c813b6eeb9f687c5128ce50 

Thanks for your help!

**Pull request closed without merging**
